sudo: false
language: java
before_script:
  - cd src
script: mvn install
jdk:
  - openjdk7
branches:
  only:
  - master
notifications:
  email:
    recipients:
        - damiano.giampaoli@geo-solutions.it
        - stefano.giaccio@fao.org
        - alessio.alfonsetti@fao.org
    on_success: change
    on_failure: change
os:
  - linux