language: java
script: mvn install
jdk:
- openjdk7
branches:
  only:
  - master
notifications:
  email:
  - damiano.giampaoli@geo-solutions.it
  - stefano.giaccio@fao.org
  - alessio.alfonsetti@fao.org
